name: 'Check Branch'

on:
  pull_request:

jobs:
  check_pr_origin_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR origin branch
        run: |
          if [[  ${{github.head_ref}} == 'main' && ${{github.base_ref}} == 'stage' ]]; then
            echo "PR from stage to main"
          elif  [[  ${{github.head_ref}} == 'stage' && ${{github.base_ref}} == 'dev' ]]; then
            echo "PR from dev to stage"
          else
            echo "ERROR: You cannot merge ${{github.head_ref}} to ${{github.base_ref}}."
            exit 1
          fi
