name: 'Check Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          if [[  github.base_ref == 'main' && github.head_ref != 'stage' ]]; then
            echo "PR from stage to main"
          elif  [[  github.base_ref == 'stage' && github.head_ref != 'dev' ]]; then
            echo "PR from dev to stage"
          else
            echo "ERROR: You can only merge to main from dev."
            exit 1
          fi
          
